### ISSUE TITLE
Format Tweets

### ISSUE THREAD

**Issue by sfkeller** [geometalab/Trending-Places-in-OpenStreetMap#2]
Format tweets for optimal reading... (look also carefully at the spaces). This is a current tweet: https://twitter.com/trending_places/status/720178731164286977
"2016-04-11's top trending places in #OSM:Mytishchi(RU) ?????????? ???????? ?????????(RU) ...Explain why!" 
This could be reformatted like this:
"Top trending places in #OSM 4/11: Mytishchi (RU), ?????????? ???????? ????????? (RU), //Fill places up to max. chars//... Can you explain why?"

**Comment by BhavyaLight** [comment]
@sfkeller I changed the date syntax but at present it already fills the places with max characters, however, if the name of a place is longer than the maximum characters, I cut it off even earlier. E.g.
"Top trending places in #OSM 4/11: Mytishchi (RU), Oberharz am...(DE), //Next place name is bigger than max characters//... Can you explain why?"
However, right now this is done in the increasing order of trends, some place with a smaller name might be in the list later on, so would you like me to not follow the order?
